export const links = {
  company: "https://democra.ai/",
  github: "https://github.com/tao-shen",
  scholar: "https://scholar.google.com/citations?user=MeaDj20AAAAJ&hl=en",
  email: "tao.shen@zju.edu.cn",
  businessEmail: "hi@democra.ai",
  x: "https://x.com/tao_shen_",
  orcid: "https://orcid.org/0000-0003-0819-9782",
};

export const products = [
  {
    name: "Candy",
    type: ["Open-source product", "开源产品"],
    image: "candy.svg",
    title: ["Expertise, ready to run.", "让专业能力，成为可用的技能。"],
    description: [
      "A marketplace to discover, run, and create AI agent skills. Reusable expertise meets real tasks, right in the browser.",
      "在浏览器中发现、运行和创建 AI 智能体技能，将可复用的专业知识与真实任务连接起来。",
    ],
    tags: ["Agent skills", "Browser execution", "Open source"],
    url: "https://candy.democra.ai/",
    code: "https://github.com/democra-ai/candy-shop",
    action: ["Explore Candy", "探索 Candy"],
  },
  {
    name: "AIR",
    type: ["Interactive research", "交互式研究"],
    image: "air.svg",
    title: ["Understanding AI. Understanding our work.", "理解 AI，也重新理解我们的工作。"],
    description: [
      "An interactive exploration of AI and work. Sixteen questions invite you to examine the knowledge, judgment, risk, and human presence behind what you do.",
      "一个探索 AI 如何改变工作的交互式项目。通过 16 个问题，从知识、评价、风险与人的在场价值出发，重新审视自己的工作。",
    ],
    tags: ["Future of work", "Research to product"],
    url: "https://air.democra.ai/",
    code: "https://github.com/democra-ai/air-quiz",
    action: ["Discover AIR", "体验 AIR"],
  },
  {
    name: "Nativize",
    type: ["AI engineering service", "AI 工程服务"],
    image: "nativize.svg",
    title: ["AI belongs in the workflow.", "让 AI 进入真实的工作流程。"],
    description: [
      "Forward-deployed engineering for organizations adopting AI. We work with teams to rethink workflows, integrate agents, and build AI into everyday operations.",
      "与企业团队并肩工作，重构业务流程、集成智能体，让 AI 系统进入真实的日常运营。",
    ],
    tags: ["Forward-deployed engineering", "AI-native workflows"],
    url: "https://democra.ai/ai-native",
    action: ["Meet Nativize", "了解 Nativize"],
  },
];

export const directions = [
  {
    key: "federated",
    label: ["Collaborate", "协同"],
    subtitle: ["Federated & heterogeneous learning", "联邦学习与异构协同"],
    description: [
      "How can different models learn together without pooling their data? My research explores collaboration across diverse models, devices, and data distributions.",
      "当模型、设备和数据各不相同时，如何在不集中原始数据的前提下共同学习？我的研究从异构联邦学习出发，探索有效的模型协同。",
    ],
    anchor: "Federated mutual learning",
    dates: "2020–2025",
  },
  {
    key: "distributed",
    label: ["Distribute", "分布"],
    subtitle: ["Distributed AI & edge intelligence", "分布式 AI 与边缘智能"],
    description: [
      "Making large-model training more accessible through distributed resources. This work asks how edge devices and collaborative infrastructure can contribute to foundation models.",
      "探索如何利用分布式资源降低大模型训练的参与门槛，让边缘设备与协同基础设施成为基础模型的一部分。",
    ],
    anchor: "Will LLMs Scaling Hit the Wall?",
    dates: "2023–2025",
  },
  {
    key: "models",
    label: ["Compose", "组合"],
    subtitle: ["Reusable & adaptable model capabilities", "可复用、可适配的模型能力"],
    description: [
      "Understanding how knowledge can be shared, combined, and retained across models, including model merging, LoRA experts, and multimodal adaptation.",
      "研究如何在模型之间共享、组合与保留知识，关注模型融合、LoRA 专家以及多模态模型适配。",
    ],
    anchor: "Model Tailor",
    dates: "2024–2025",
  },
];

export const copy = {
  en: {
    nav: ["Building", "Research", "Publications", "Journey"],
    contact: "Get in touch",
    skip: "Skip to content",
    role: "Founder & CEO",
    roleLong: "Founder & CEO, Democra AI",
    subtitle: "Researcher by training. Builder by choice.",
    affiliation: "DEMOCRA AI, INC.",
    degree: "Ph.D. · Zhejiang University",
    degreeLabel: "ACADEMIC ROOTS",
    focusLabel: "WORKING ON",
    focus: "AI democratization",
    yearLabel: "A NEW CHAPTER",
    year: "Research → entrepreneurship, 2025",
    currentLabel: "WHAT I’M BUILDING",
    current:
      "I’m building Democra AI to make AI more accessible—and to help people retain agency, ownership, and a share in the value of their expertise.",
    aboutLabel: "THE ROAD HERE",
    about:
      "I completed my Ph.D. at Zhejiang University in 2025, advised by Fei Wu and Chao Wu. My work on federated learning and distributed intelligence now informs the products I build.",
    elsewhere: "FIND ME ELSEWHERE",
    scholar: "Google Scholar",
    email: "Email",
    github: "GitHub",
    company: "Democra AI",
    chapter1: "01 / THE ENTREPRENEURIAL CHAPTER",
    building: "Building at Democra",
    buildingSub: "From distributed intelligence to shared opportunity.",
    mission: "The question that connects my research and my company: how can more people participate in AI—and benefit from it?",
    missionSmall:
      "Since completing my Ph.D. in 2025, I’ve been bringing that question into products: tools for sharing expertise, understanding change, and putting AI to work.",
    visitCompany: "Visit democra.ai",
    productsLabel: "PRODUCTS & PRACTICE",
    code: "Source",
    chapter2: "02 / THE RESEARCH FOUNDATIONS",
    research: "Research that carries forward",
    researchSub: "My doctoral work at Zhejiang University, 2019–2025.",
    researchIntro:
      "Before building products, I studied how intelligence can be learned and shared across heterogeneous systems. Three connected directions continue to shape my work.",
    relatedPaper: "Explore related papers",
    chapter3: "03 / PUBLICATIONS",
    pubs: "Ideas, in print",
    pubsSub: "Selected work and the wider research record.",
    selected: "Selected",
    all: "All publications",
    firstAuthor: "First / co-first author",
    search: "Search title, author, or venue",
    searchLabel: "Search publications",
    noResults: "No papers match this search.",
    reset: "Clear filters",
    paper: "Paper",
    citation: "Cite",
    copyCitation: "Copy BibTeX",
    copied: "Copied",
    copyError: "Select and copy the text below.",
    results: "papers",
    completeRecord: "View Google Scholar",
    pubNote: "Conference papers, journal articles, and preprints are labeled individually. Research collaborations continued beyond my Ph.D.",
    chapter4: "04 / THE JOURNEY",
    journey: "A change of chapter. A continuing question.",
    now: "2025 — PRESENT",
    founder: "Founder & CEO",
    founderDetail: "Democra AI, Inc.",
    founderText: "Building products and services around AI democratization: capability, agency, and ownership.",
    phd: "Ph.D. in Computer Science",
    phdDetail: "Zhejiang University",
    phdText: "Advised by Prof. Fei Wu and Prof. Chao Wu. Research in federated learning, distributed AI, and collaborative models.",
    contactLabel: "LET’S TALK",
    contactTitle: "Good ideas get better\nin good company.",
    contactText: "I’m interested in conversations about AI products, research, and ways to make advanced AI useful to more people.",
    emailMe: "Say hello",
    academicContact: "Academic correspondence",
    back: "Back to top",
    footer: "Researcher. Founder. Working toward AI for everyone.",
    updated: "Updated October 2026",
    menuOpen: "Open navigation",
    menuClose: "Close navigation",
    themeDark: "Switch to dark theme",
    themeLight: "Switch to light theme",
    copyEmail: "Copy email address",
  },
  zh: {
    nav: ["创业", "研究", "论文", "经历"],
    contact: "联系我",
    skip: "跳转到正文",
    role: "创始人兼 CEO",
    roleLong: "Democra AI 创始人兼 CEO",
    subtitle: "从研究出发，把想法做成产品。",
    affiliation: "DEMOCRA AI, INC.",
    degree: "浙江大学 · 博士",
    degreeLabel: "学术背景",
    focusLabel: "当前方向",
    focus: "AI 民主化",
    yearLabel: "新的篇章",
    year: "2025，从学术研究走向创业",
    currentLabel: "现在正在做的事",
    current: "我正在建设 Democra AI，希望让更多人能够使用 AI 创造价值，保有对自身知识的控制权，并从自己的贡献中获益。",
    aboutLabel: "从哪里出发",
    about: "我于 2025 年获得浙江大学博士学位，师从吴飞教授和吴朝教授。此前对联邦学习与分布式智能的研究，正成为今天构建产品的基础。",
    elsewhere: "找到我",
    scholar: "Google Scholar",
    email: "电子邮件",
    github: "GitHub",
    company: "Democra AI",
    chapter1: "01 / 创业篇章",
    building: "在 Democra，把想法变成产品",
    buildingSub: "从分布式智能，到更多人的机会。",
    mission: "贯穿研究与创业的同一个问题：如何让更多人参与 AI，并从中受益？",
    missionSmall: "2025 年博士毕业后，我开始通过产品探索答案：让专业能力得以复用，让人们理解 AI 带来的变化，也让 AI 进入真实的工作。",
    visitCompany: "访问 democra.ai",
    productsLabel: "产品与实践",
    code: "源代码",
    chapter2: "02 / 学术基础",
    research: "延续至今的研究问题",
    researchSub: "浙江大学博士阶段，2019—2025。",
    researchIntro: "在构建产品之前，我研究智能如何在异构系统中被学习、共享与组合。这三个相互连接的方向，仍在影响今天的工作。",
    relatedPaper: "查看相关论文",
    chapter3: "03 / 论文发表",
    pubs: "写下的探索",
    pubsSub: "代表性工作，以及持续积累的研究。",
    selected: "代表作",
    all: "全部论文",
    firstAuthor: "第一 / 共同第一作者",
    search: "搜索标题、作者或期刊会议",
    searchLabel: "搜索论文",
    noResults: "没有找到符合条件的论文。",
    reset: "清除筛选",
    paper: "论文",
    citation: "引用",
    copyCitation: "复制 BibTeX",
    copied: "已复制",
    copyError: "请选中下方文本手动复制。",
    results: "篇论文",
    completeRecord: "查看 Google Scholar",
    pubNote: "会议论文、期刊文章与预印本分别标注。部分学术合作延续至博士毕业之后。",
    chapter4: "04 / 个人经历",
    journey: "篇章在变，问题一以贯之。",
    now: "2025 — 至今",
    founder: "创始人兼 CEO",
    founderDetail: "Democra AI, Inc.",
    founderText: "围绕 AI 民主化构建产品与服务，关注能力普及、自主权与知识所有权。",
    phd: "计算机科学与技术博士",
    phdDetail: "浙江大学",
    phdText: "师从吴飞教授和吴朝教授，研究联邦学习、分布式 AI 与模型协同。",
    contactLabel: "保持交流",
    contactTitle: "让好的想法，\n遇到同行的人。",
    contactText: "欢迎交流 AI 产品、学术研究，以及如何让更多人真正用上先进的 AI。",
    emailMe: "聊一聊",
    academicContact: "学术交流",
    back: "回到顶部",
    footer: "研究者，创业者。让 AI 的机会属于更多人。",
    updated: "更新于 2026 年 10 月",
    menuOpen: "打开导航",
    menuClose: "关闭导航",
    themeDark: "切换至深色模式",
    themeLight: "切换至浅色模式",
    copyEmail: "复制邮箱地址",
  },
};
