export const profile = {
  chineseName: "沈弢",
  portrait: "tao-shen-scholar.jpg",
  education: [
    {
      dates: "2015 — 2018",
      degree: ["M.S. in Control Science & Engineering", "控制科学与工程硕士"],
      school: ["Zhejiang University", "浙江大学"],
    },
    {
      dates: "2011 — 2015",
      degree: ["B.S. in Automation", "自动化学士"],
      school: ["China University of Petroleum", "中国石油大学（华东）"],
    },
  ],
};

export const publications = [
  {
    id: "each-rank-2026",
    year: 2026,
    title: "Each Rank Could be an Expert: Single-Ranked Mixture of Experts LoRA for Multi-task Learning",
    authors:
      "Ziyu Zhao, Yixiao Zhou, Xin Yu, Zhi Zhang, Didi Zhu, Tao Shen, Zexi Li, Jinluan Yang, Xuwu Wang, Jing Su, Kun Kuang, Zhongyu Wei, Fei Wu, Yu Cheng",
    venue: "KDD 2026",
    url: "https://doi.org/10.1145/3770854.3780222",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    bibtex:
      "@inproceedings{each-rank-2026,\n  title = {{Each Rank Could be an Expert: Single-Ranked Mixture of Experts LoRA for Multi-task Learning}},\n  author = {Zhao, Ziyu and Zhou, Yixiao and Yu, Xin and Zhang, Zhi and Zhu, Didi and Shen, Tao and Li, Zexi and Yang, Jinluan and Wang, Xuwu and Su, Jing and Kuang, Kun and Wei, Zhongyu and Wu, Fei and Cheng, Yu},\n  year = {2026},\n  booktitle = {Proceedings of the 32nd ACM SIGKDD Conference on Knowledge Discovery and Data Mining},\n  doi = {10.1145/3770854.3780222},\n  url = {https://doi.org/10.1145/3770854.3780222}\n}",
  },
  {
    id: "watch-wider-2026",
    year: 2026,
    title: "Watch Wider and Think Deeper: Collaborative Cross-modal Chain-of-Thought for Complex Visual Reasoning",
    authors: "Wenting Lu, Didi Zhu, Tao Shen, Donglin Zhu, Ayong Ye, Chao Wu",
    venue: "arXiv preprint arXiv:2601.02422",
    url: "https://arxiv.org/abs/2601.02422",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["distributed", "models"],
    bibtex:
      "@misc{watch-wider-2026,\n  title = {{Watch Wider and Think Deeper: Collaborative Cross-modal Chain-of-Thought for Complex Visual Reasoning}},\n  author = {Lu, Wenting and Zhu, Didi and Shen, Tao and Zhu, Donglin and Ye, Ayong and Wu, Chao},\n  year = {2026},\n  note = {arXiv preprint arXiv:2601.02422},\n  url = {https://arxiv.org/abs/2601.02422}\n}",
  },
  {
    id: "fedeve-2025",
    year: 2025,
    title: "FedEve: On Bridging the Client Drift and Period Drift for Cross-device Federated Learning",
    authors: "Tao Shen, Zexi Li, Didi Zhu, Ziyu Zhao, Chao Wu, Fei Wu",
    venue: "arXiv · Preprint · 2025",
    url: "https://arxiv.org/abs/2508.14539",
    selected: true,
    firstAuthor: true,
    coFirst: false,
    topics: ["federated", "distributed"],
    summary: [
      "Introduces a predict–observe method that treats client drift and the cross-device period drift together and uses their interaction to reduce update variance.",
      "同时建模客户端漂移与跨周期漂移，通过预测和观测协同降低跨设备联邦学习的更新方差。",
    ],
    code: "https://github.com/tao-shen/fedeve",
    bibtex:
      "@misc{fedeve-2025,\n  title = {{FedEve: On Bridging the Client Drift and Period Drift for Cross-device Federated Learning}},\n  author = {Shen, Tao and Li, Zexi and Zhu, Didi and Zhao, Ziyu and Wu, Chao and Wu, Fei},\n  year = {2025},\n  note = {arXiv preprint arXiv:2508.14539},\n  url = {https://arxiv.org/abs/2508.14539}\n}",
  },
  {
    id: "fedmcon-journal-2025",
    year: 2025,
    title: "FedMcon: an adaptive aggregation method for federated learning via meta controller",
    authors: "Tao Shen, Zexi Li, Ziyu Zhao, Didi Zhu, Zheqi Lv, Kun Kuang, Shengyu Zhang, Chao Wu, Fei Wu",
    venue: "FITEE · Journal · 2025",
    url: "https://jzus.zju.edu.cn/iparticle.php?doi=10.1631%2FFITEE.2400530",
    selected: true,
    firstAuthor: true,
    coFirst: false,
    topics: ["federated"],
    summary: [
      "Uses a meta-controller to adapt aggregation weights to heterogeneous federated clients.",
      "利用元控制器，为异构客户端学习自适应的联邦聚合权重。",
    ],
    bibtex:
      "@article{fedmcon-journal-2025,\n  title = {{FedMcon: an adaptive aggregation method for federated learning via meta controller}},\n  author = {Shen, Tao and Li, Zexi and Zhao, Ziyu and Zhu, Didi and Lv, Zheqi and Kuang, Kun and Zhang, Shengyu and Wu, Chao and Wu, Fei},\n  year = {2025},\n  journal = {Frontiers of Information Technology \\& Electronic Engineering 26(8), 1378–1393},\n  doi = {10.1631/FITEE.2400530},\n  url = {https://jzus.zju.edu.cn/iparticle.php?doi=10.1631%2FFITEE.2400530}\n}",
  },
  {
    id: "lora-lego-2025",
    year: 2025,
    title: "Merging LoRAs like Playing LEGO: Pushing the Modularity of LoRA to Extremes Through Rank-Wise Clustering",
    authors: "Ziyu Zhao, Tao Shen, Didi Zhu, Zexi Li, Jing Su, Xuwu Wang, Kun Kuang, Fei Wu",
    venue: "ICLR 2025",
    url: "https://openreview.net/forum?id=j6fsbpAllN",
    selected: true,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    summary: [
      "Introduces LoRA-LEGO, which clusters rank-level minimal semantic units to merge adapters with flexible output rank.",
      "将 LoRA 拆分为秩级别的语义单元，通过聚类实现更灵活的适配器组合。",
    ],
    bibtex:
      "@inproceedings{lora-lego-2025,\n  title = {{Merging LoRAs like Playing LEGO: Pushing the Modularity of LoRA to Extremes Through Rank-Wise Clustering}},\n  author = {Zhao, Ziyu and Shen, Tao and Zhu, Didi and Li, Zexi and Su, Jing and Wang, Xuwu and Kuang, Kun and Wu, Fei},\n  year = {2025},\n  booktitle = {ICLR 2025},\n  url = {https://openreview.net/forum?id=j6fsbpAllN}\n}",
  },
  {
    id: "llm-scaling-2025",
    year: 2025,
    title: "Will LLMs Scaling Hit the Wall? Breaking Barriers via Distributed Resources on Massive Edge Devices",
    authors: "Tao Shen, Didi Zhu, Ziyu Zhao, Zexi Li, Chao Wu, Fei Wu",
    venue: "arXiv · Position paper · 2025",
    url: "https://arxiv.org/abs/2503.08223",
    selected: true,
    firstAuthor: true,
    coFirst: true,
    topics: ["distributed"],
    summary: [
      "A position paper arguing that massive edge-device resources can make large-model training more inclusive by combining distributed data and compute.",
      "探索如何将海量边缘设备的数据与算力连接起来，让更多人参与大模型训练。",
    ],
    bibtex:
      "@misc{llm-scaling-2025,\n  title = {{Will LLMs Scaling Hit the Wall? Breaking Barriers via Distributed Resources on Massive Edge Devices}},\n  author = {Shen, Tao and Zhu, Didi and Zhao, Ziyu and Li, Zexi and Wu, Chao and Wu, Fei},\n  year = {2025},\n  note = {arXiv preprint arXiv:2503.08223},\n  url = {https://arxiv.org/abs/2503.08223}\n}",
  },
  {
    id: "fedcfa-2025",
    year: 2025,
    title: "FedCFA: Alleviating Simpson’s Paradox in Model Aggregation with Counterfactual Federated Learning",
    authors: "Zhonghua Jiang, Jimin Xu, Shengyu Zhang, Tao Shen, Jiwei Li, Kun Kuang, Haibin Cai, Fei Wu",
    venue: "AAAI 2025, 39(17), 17662–17670",
    url: "https://doi.org/10.1609/aaai.v39i17.33942",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@inproceedings{fedcfa-2025,\n  title = {{FedCFA: Alleviating Simpson’s Paradox in Model Aggregation with Counterfactual Federated Learning}},\n  author = {Jiang, Zhonghua and Xu, Jimin and Zhang, Shengyu and Shen, Tao and Li, Jiwei and Kuang, Kun and Cai, Haibin and Wu, Fei},\n  year = {2025},\n  booktitle = {AAAI 2025, 39(17), 17662–17670},\n  doi = {10.1609/aaai.v39i17.33942},\n  url = {https://doi.org/10.1609/aaai.v39i17.33942}\n}",
  },
  {
    id: "fedgucci-2025",
    year: 2025,
    title: "FedGuCci: Making Local Models More Connected in Landscape for Federated Learning",
    authors: "Zexi Li, Jie Lin, Zhiqi Li, Didi Zhu, Tao Shen, Tao Lin, Chao Wu, Nicholas D. Lane",
    venue: "KDD 2025, pp. 1659–1670",
    url: "https://doi.org/10.1145/3711896.3737037",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@inproceedings{fedgucci-2025,\n  title = {{FedGuCci: Making Local Models More Connected in Landscape for Federated Learning}},\n  author = {Li, Zexi and Lin, Jie and Li, Zhiqi and Zhu, Didi and Shen, Tao and Lin, Tao and Wu, Chao and Lane, Nicholas D.},\n  year = {2025},\n  booktitle = {KDD 2025, pp. 1659–1670},\n  doi = {10.1145/3711896.3737037},\n  url = {https://doi.org/10.1145/3711896.3737037}\n}",
  },
  {
    id: "flowertune-2025",
    year: 2025,
    title: "FlowerTune: A Cross-domain Benchmark for Federated Fine-tuning of Large Language Models",
    authors:
      "Yan Gao, Massimo Roberto Scamarcia, Javier Fernandez-Marques, Mohammad Naseri, Chong Shen Ng, Dimitris Stripelis, Zexi Li, Tao Shen, Jiamu Bai, Daoyuan Chen, Zikai Zhang, Rui Hu, InSeo Song, Lee KangYoon, Hong Jia, Ting Dang, Junyan Wang, Zheyuan Liu, Daniel Janes Beutel, Lingjuan Lyu, Nicholas D. Lane",
    venue: "NeurIPS 2025",
    url: "https://arxiv.org/abs/2506.02961",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@inproceedings{flowertune-2025,\n  title = {{FlowerTune: A Cross-domain Benchmark for Federated Fine-tuning of Large Language Models}},\n  author = {Gao, Yan and Scamarcia, Massimo Roberto and Fernandez-Marques, Javier and Naseri, Mohammad and Ng, Chong Shen and Stripelis, Dimitris and Li, Zexi and Shen, Tao and Bai, Jiamu and Chen, Daoyuan and Zhang, Zikai and Hu, Rui and Song, InSeo and KangYoon, Lee and Jia, Hong and Dang, Ting and Wang, Junyan and Liu, Zheyuan and Beutel, Daniel Janes and Lyu, Lingjuan and Lane, Nicholas D.},\n  year = {2025},\n  booktitle = {NeurIPS 38},\n  url = {https://arxiv.org/abs/2506.02961}\n}",
  },
  {
    id: "neuron-anchors-2025",
    year: 2025,
    title: "Improving Model Fusion by Training-time Neuron Alignment with Fixed Neuron Anchors",
    authors: "Zexi Li, Zhiqi Li, Jie Lin, Tao Shen, Jun Xiao, Yike Guo, Tao Lin, Chao Wu",
    venue: "IEEE TPAMI · 2025",
    url: "https://doi.org/10.1109/TPAMI.2025.3624314",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    bibtex:
      "@article{neuron-anchors-2025,\n  title = {{Improving Model Fusion by Training-time Neuron Alignment with Fixed Neuron Anchors}},\n  author = {Li, Zexi and Li, Zhiqi and Lin, Jie and Shen, Tao and Xiao, Jun and Guo, Yike and Lin, Tao and Wu, Chao},\n  year = {2025},\n  journal = {IEEE Transactions on Pattern Analysis and Machine Intelligence},\n  doi = {10.1109/TPAMI.2025.3624314},\n  url = {https://doi.org/10.1109/TPAMI.2025.3624314}\n}",
  },
  {
    id: "knowledge-roadmap-2025",
    year: 2025,
    title: "Knowledge-Empowered, Collaborative, and Co-Evolving AI Models: The Post-LLM Roadmap",
    authors:
      "Fei Wu, Tao Shen, Thomas Bäck, Jingyuan Chen, Gang Huang, Yaochu Jin, Kun Kuang, Mengze Li, Cewu Lu, Jiaxu Miao, Yongwei Wang, Ying Wei, Fan Wu, Junchi Yan, Hongxia Yang, Yi Yang, Shengyu Zhang, Zhou Zhao, Yueting Zhuang, Yunhe Pan",
    venue: "Engineering 44, 87–100",
    url: "https://doi.org/10.1016/j.eng.2024.12.008",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["distributed", "models"],
    bibtex:
      "@article{knowledge-roadmap-2025,\n  title = {{Knowledge-Empowered, Collaborative, and Co-Evolving AI Models: The Post-LLM Roadmap}},\n  author = {Wu, Fei and Shen, Tao and Bäck, Thomas and Chen, Jingyuan and Huang, Gang and Jin, Yaochu and Kuang, Kun and Li, Mengze and Lu, Cewu and Miao, Jiaxu and Wang, Yongwei and Wei, Ying and Wu, Fan and Yan, Junchi and Yang, Hongxia and Yang, Yi and Zhang, Shengyu and Zhao, Zhou and Zhuang, Yueting and Pan, Yunhe},\n  year = {2025},\n  journal = {Engineering 44, 87–100},\n  doi = {10.1016/j.eng.2024.12.008},\n  url = {https://doi.org/10.1016/j.eng.2024.12.008}\n}",
  },
  {
    id: "remedy-2025",
    year: 2025,
    title: "Remedy: Recipe Merging Dynamics in Large Vision-Language Models",
    authors: "Didi Zhu, Yibing Song, Tao Shen, Ziyu Zhao, Jinluan Yang, Min Zhang, Chao Wu",
    venue: "ICLR 2025",
    url: "https://openreview.net/forum?id=iX7eHHE5Tx",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    bibtex:
      "@inproceedings{remedy-2025,\n  title = {{Remedy: Recipe Merging Dynamics in Large Vision-Language Models}},\n  author = {Zhu, Didi and Song, Yibing and Shen, Tao and Zhao, Ziyu and Yang, Jinluan and Zhang, Min and Wu, Chao},\n  year = {2025},\n  booktitle = {ICLR 2025},\n  url = {https://openreview.net/forum?id=iX7eHHE5Tx}\n}",
  },
  {
    id: "model-tailor-2024",
    year: 2024,
    title: "Model Tailor: Mitigating Catastrophic Forgetting in Multi-modal Large Language Models",
    authors: "Didi Zhu, Zhongyisun Sun, Zexi Li, Tao Shen, Ke Yan, Shouhong Ding, Chao Wu, Kun Kuang",
    venue: "ICML 2024",
    url: "https://proceedings.mlr.press/v235/zhu24l.html",
    selected: true,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    summary: [
      "Preserves most pretrained parameters while patching a small set of fine-tuned parameters to reduce catastrophic forgetting in multimodal LLMs.",
      "通过少量参数补丁，在多模态大模型微调后保留已有能力，缓解灾难性遗忘。",
    ],
    code: "https://github.com/didizhu-judy/Model-Tailor",
    bibtex:
      "@inproceedings{model-tailor-2024,\n  title = {{Model Tailor: Mitigating Catastrophic Forgetting in Multi-modal Large Language Models}},\n  author = {Zhu, Didi and Sun, Zhongyisun and Li, Zexi and Shen, Tao and Yan, Ke and Ding, Shouhong and Wu, Chao and Kuang, Kun},\n  year = {2024},\n  booktitle = {ICML 2024, Proceedings of Machine Learning Research 235, 62581–62598},\n  url = {https://proceedings.mlr.press/v235/zhu24l.html}\n}",
  },
  {
    id: "adaptive-aggregation-2024",
    year: 2024,
    title: "An Adaptive Aggregation Method for Federated Learning via Meta Controller",
    authors: "Tao Shen, Zexi Li, Ziyu Zhao, Didi Zhu, Zheqi Lv, Shengyu Zhang, Kun Kuang, Fei Wu",
    venue: "ACM Multimedia Asia 2024",
    url: "https://doi.org/10.1145/3700410.3702124",
    selected: false,
    firstAuthor: true,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@inproceedings{adaptive-aggregation-2024,\n  title = {{An Adaptive Aggregation Method for Federated Learning via Meta Controller}},\n  author = {Shen, Tao and Li, Zexi and Zhao, Ziyu and Zhu, Didi and Lv, Zheqi and Zhang, Shengyu and Kuang, Kun and Wu, Fei},\n  year = {2024},\n  booktitle = {ACM Multimedia Asia 2024, pp. 1–8},\n  doi = {10.1145/3700410.3702124},\n  url = {https://doi.org/10.1145/3700410.3702124}\n}",
  },
  {
    id: "deconfounded-2024",
    year: 2024,
    title: "Deconfounded hierarchical multi-granularity classification",
    authors: "Ziyu Zhao, Leilei Gan, Tao Shen, Kun Kuang, Fei Wu",
    venue: "Computer Vision and Image Understanding 248, 104108",
    url: "https://doi.org/10.1016/j.cviu.2024.104108",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    bibtex:
      "@article{deconfounded-2024,\n  title = {{Deconfounded hierarchical multi-granularity classification}},\n  author = {Zhao, Ziyu and Gan, Leilei and Shen, Tao and Kuang, Kun and Wu, Fei},\n  year = {2024},\n  journal = {Computer Vision and Image Understanding 248, 104108},\n  doi = {10.1016/j.cviu.2024.104108},\n  url = {https://doi.org/10.1016/j.cviu.2024.104108}\n}",
  },
  {
    id: "group-connectivity-2024",
    year: 2024,
    title: "Improving Group Connectivity for Generalization of Federated Deep Learning",
    authors: "Zexi Li, Jie Lin, Zhiqi Li, Didi Zhu, Rui Ye, Tao Shen, Tao Lin, Chao Wu",
    venue: "International Workshop on Federated Foundation Models (FedFM) 2024",
    url: "https://openreview.net/pdf?id=vGyB8PVl4C",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@article{group-connectivity-2024,\n  title = {{Improving Group Connectivity for Generalization of Federated Deep Learning}},\n  author = {Li, Zexi and Lin, Jie and Li, Zhiqi and Zhu, Didi and Ye, Rui and Shen, Tao and Lin, Tao and Wu, Chao},\n  year = {2024},\n  journal = {International Workshop on Federated Foundation Models (FedFM) 2024},\n  url = {https://openreview.net/pdf?id=vGyB8PVl4C}\n}",
  },
  {
    id: "retrieval-lora-2024",
    year: 2024,
    title: "Retrieval-Augmented Mixture of LoRA Experts for Uploadable Machine Learning",
    authors: "Ziyu Zhao, Leilei Gan, Guoyin Wang, Yuwei Hu, Tao Shen, Hongxia Yang, Kun Kuang, Fei Wu",
    venue: "arXiv preprint arXiv:2406.16989",
    url: "https://arxiv.org/abs/2406.16989",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["models"],
    bibtex:
      "@misc{retrieval-lora-2024,\n  title = {{Retrieval-Augmented Mixture of LoRA Experts for Uploadable Machine Learning}},\n  author = {Zhao, Ziyu and Gan, Leilei and Wang, Guoyin and Hu, Yuwei and Shen, Tao and Yang, Hongxia and Kuang, Kun and Wu, Fei},\n  year = {2024},\n  note = {arXiv preprint arXiv:2406.16989},\n  url = {https://arxiv.org/abs/2406.16989}\n}",
  },
  {
    id: "fml-2023",
    year: 2023,
    title: "Federated mutual learning: a collaborative machine learning method for heterogeneous data, models, and objectives",
    authors: "Tao Shen, Jie Zhang, Xinkang Jia, Fengda Zhang, Zheqi Lv, Kun Kuang, Chao Wu, Fei Wu",
    venue: "FITEE · Journal · 2023",
    url: "https://jzus.zju.edu.cn/opentxt.php?doi=10.1631%2FFITEE.2300098",
    selected: true,
    firstAuthor: true,
    coFirst: false,
    topics: ["federated"],
    summary: [
      "Presents federated mutual learning, allowing clients to jointly learn a generalized model while retaining personalized models under data, objective, and model heterogeneity.",
      "在数据、模型与目标异构的条件下，让客户端协同学习，并保留各自的个性化模型。",
    ],
    code: "https://github.com/tao-shen/FML",
    bibtex:
      "@article{fml-2023,\n  title = {{Federated mutual learning: a collaborative machine learning method for heterogeneous data, models, and objectives}},\n  author = {Shen, Tao and Zhang, Jie and Jia, Xinkang and Zhang, Fengda and Lv, Zheqi and Kuang, Kun and Wu, Chao and Wu, Fei},\n  year = {2023},\n  journal = {Frontiers of Information Technology \\& Electronic Engineering 24(10), 1390–1402},\n  doi = {10.1631/FITEE.2300098},\n  url = {https://jzus.zju.edu.cn/opentxt.php?doi=10.1631%2FFITEE.2300098}\n}",
  },
  {
    id: "duet-2023",
    year: 2023,
    title: "DUET: A Tuning-Free Device-Cloud Collaborative Parameters Generation Framework for Efficient Device Model Generalization",
    authors:
      "Zheqi Lv, Wenqiao Zhang, Shengyu Zhang, Kun Kuang, Feng Wang, Yongwei Wang, Zhengyu Chen, Tao Shen, Hongxia Yang, Beng Chin Ooi, Fei Wu",
    venue: "The Web Conference 2023, pp. 3077–3085",
    url: "https://doi.org/10.1145/3543507.3583451",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["distributed"],
    bibtex:
      "@inproceedings{duet-2023,\n  title = {{DUET: A Tuning-Free Device-Cloud Collaborative Parameters Generation Framework for Efficient Device Model Generalization}},\n  author = {Lv, Zheqi and Zhang, Wenqiao and Zhang, Shengyu and Kuang, Kun and Wang, Feng and Wang, Yongwei and Chen, Zhengyu and Shen, Tao and Yang, Hongxia and Ooi, Beng Chin and Wu, Fei},\n  year = {2023},\n  booktitle = {The Web Conference 2023, pp. 3077–3085},\n  doi = {10.1145/3543507.3583451},\n  url = {https://doi.org/10.1145/3543507.3583451}\n}",
  },
  {
    id: "furl-2023",
    year: 2023,
    title: "Federated unsupervised representation learning",
    authors: "Fengda Zhang, Kun Kuang, Long Chen, Zhaoyang You, Tao Shen, Jun Xiao, Yin Zhang, Chao Wu, Fei Wu, Yueting Zhuang, Xiaolin Li",
    venue: "Frontiers of Information Technology & Electronic Engineering 24(8), 1181–1193",
    url: "https://jzus.zju.edu.cn/iparticle.php?doi=10.1631%2FFITEE.2200268",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["federated"],
    bibtex:
      "@article{furl-2023,\n  title = {{Federated unsupervised representation learning}},\n  author = {Zhang, Fengda and Kuang, Kun and Chen, Long and You, Zhaoyang and Shen, Tao and Xiao, Jun and Zhang, Yin and Wu, Chao and Wu, Fei and Zhuang, Yueting and Li, Xiaolin},\n  year = {2023},\n  journal = {Frontiers of Information Technology \\& Electronic Engineering 24(8), 1181–1193},\n  doi = {10.1631/FITEE.2200268},\n  url = {https://jzus.zju.edu.cn/iparticle.php?doi=10.1631%2FFITEE.2200268}\n}",
  },
  {
    id: "edge-cloud-2022",
    year: 2022,
    title: "Edge-Cloud Polarization and Collaboration: A Comprehensive Survey for AI",
    authors:
      "Jiangchao Yao, Shengyu Zhang, Yang Yao, Feng Wang, Jianxin Ma, Jianwei Zhang, Yunfei Chu, Luo Ji, Kunyang Jia, Tao Shen, Anpeng Wu, Fengda Zhang, Ziqi Tan, Kun Kuang, Chao Wu, Fei Wu, Jingren Zhou, Hongxia Yang",
    venue: "IEEE Transactions on Knowledge and Data Engineering 35(7), 6866–6886",
    url: "https://doi.org/10.1109/TKDE.2022.3178211",
    selected: false,
    firstAuthor: false,
    coFirst: false,
    topics: ["distributed"],
    bibtex:
      "@article{edge-cloud-2022,\n  title = {{Edge-Cloud Polarization and Collaboration: A Comprehensive Survey for AI}},\n  author = {Yao, Jiangchao and Zhang, Shengyu and Yao, Yang and Wang, Feng and Ma, Jianxin and Zhang, Jianwei and Chu, Yunfei and Ji, Luo and Jia, Kunyang and Shen, Tao and Wu, Anpeng and Zhang, Fengda and Tan, Ziqi and Kuang, Kun and Wu, Chao and Wu, Fei and Zhou, Jingren and Yang, Hongxia},\n  year = {2022},\n  journal = {IEEE Transactions on Knowledge and Data Engineering 35(7), 6866–6886},\n  doi = {10.1109/TKDE.2022.3178211},\n  url = {https://doi.org/10.1109/TKDE.2022.3178211}\n}",
  },
  {
    id: "federated-graph-2021",
    year: 2021,
    title: "Federated Graph Learning—A Position Paper",
    authors: "Huanding Zhang, Tao Shen, Fei Wu, Mingyang Yin, Hongxia Yang, Chao Wu",
    venue: "arXiv preprint arXiv:2105.11099",
    url: "https://arxiv.org/abs/2105.11099",
    selected: false,
    firstAuthor: true,
    coFirst: true,
    topics: ["federated", "distributed"],
    bibtex:
      "@misc{federated-graph-2021,\n  title = {{Federated Graph Learning—A Position Paper}},\n  author = {Zhang, Huanding and Shen, Tao and Wu, Fei and Yin, Mingyang and Yang, Hongxia and Wu, Chao},\n  year = {2021},\n  note = {arXiv preprint arXiv:2105.11099},\n  url = {https://arxiv.org/abs/2105.11099}\n}",
  },
  {
    id: "graph-power-flow-2018",
    year: 2018,
    title: "A Graph-based Power Flow Method for Balanced Distribution Systems",
    authors: "Tao Shen, Yanjun Li, Ji Xiang",
    venue: "Energies 11(3), 511",
    url: "https://www.mdpi.com/1996-1073/11/3/511",
    selected: false,
    firstAuthor: true,
    coFirst: false,
    topics: [],
    bibtex:
      "@article{graph-power-flow-2018,\n  title = {{A Graph-based Power Flow Method for Balanced Distribution Systems}},\n  author = {Shen, Tao and Li, Yanjun and Xiang, Ji},\n  year = {2018},\n  journal = {Energies 11(3), 511},\n  doi = {10.3390/en11030511},\n  url = {https://www.mdpi.com/1996-1073/11/3/511}\n}",
  },
];
